remove nextflow pull command for non existent repo
aws-samples/amazon-omics-tutorials pull request #42
Opened 2023-11-08 17:50 UTC by nbulsara

*Issue #, if available:*

*Description of changes:*
remove reference to non existent repo (secops finding)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-11-08 18:08 UTC, wleepang requested changes
Suggest removing update instructions entirely since there isn't a direct mechanism to do that apart from cloning / pulling the repo

2023-11-08 18:08 UTC, wleepang commented on example-workflows/nf-core/workflows/fastqc/docs/usage.md
>  When you run the above command, Nextflow automatically pulls the pipeline code from GitHub and stores it as a cached version. When running the pipeline after this, it will always use the cached versi
Is this section at all relevant?

2023-11-09 04:40 UTC, nbulsara commented on example-workflows/nf-core/workflows/fastqc/docs/usage.md
>  When you run the above command, Nextflow automatically pulls the pipeline code from GitHub and stores it as a cached version. When running the pipeline after this, it will always use the cached versi
not relevant, removed it

2023-11-09 06:03 UTC, wleepang approved these changes

2023-11-09 06:03 UTC, merged